require 'quality/rake/task'

Quality::Rake::Task.new do |t|
  t.skip_tools = ['flog']
  t.source_dirs = ['.']
  t.verbose = true
end

# XXX add tasks as a default directory
Dir['tasks/**/*.rake'].each { |t| load t }

task default: [:test, :clojure_quality, :quality, :ancient,
               :check_on_reflection, :slamhound, :cloverage]

task ci: [:default]
